import { Trophy, TrendingUp } from "lucide-react";
import { getTeamProjections, getNextWeekPredictions } from "@/lib/queries/projections";
import { getCurrentLeague } from "@/lib/queries/leagues";
import { PageHeader } from "@/components/page-header";
import { EmptyState } from "@/components/empty-state";
import { TeamBadge } from "@/components/team-badge";
import { MatchupPredictionCard } from "@/components/matchup-prediction-card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { fmtPoints } from "@/lib/format";
import { cn } from "@/lib/utils";

export const revalidate = 300;
export const metadata = { title: "Projections" };

export default async function ProjectionsPage() {
  const [league, teamProjections, nextWeek] = await Promise.all([
    getCurrentLeague(),
    getTeamProjections(),
    getNextWeekPredictions(),
  ]);

  const regularSeasonWeeks = (league?.playoff_week_start ?? 15) - 1;
  const playoffTeams = Number((league?.settings as { playoff_teams?: number } | undefined)?.playoff_teams ?? 4);

  return (
    <div className="flex flex-col gap-8">
      <PageHeader
        eyebrow="Projections"
        title="Season Projections"
        description={`A linear regression trained on this league's own season-over-season player scoring projects every rostered player's expected PPG for ${league?.season ?? "this season"}. That feeds a 10,000-run Monte Carlo simulation of the remaining schedule for projected records, playoff odds, and weekly win probabilities. Recomputed weekly as real results come in.`}
      />

      {teamProjections.length === 0 ? (
        <EmptyState
          icon={TrendingUp}
          title="No projections yet"
          description="Projections are generated by the weekly sync job. Check back after the next run."
        />
      ) : (
        <>
          {nextWeek.length > 0 && (
            <section className="flex flex-col gap-4">
              <h2 className="font-heading text-lg font-semibold tracking-tight">Week {nextWeek[0].week} Predictions</h2>
              <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
                {nextWeek.map((prediction) => (
                  <MatchupPredictionCard key={`${prediction.roster_id}-${prediction.opponent_roster_id}`} prediction={prediction} />
                ))}
              </div>
            </section>
          )}

          <section className="flex flex-col gap-4">
            <h2 className="font-heading text-lg font-semibold tracking-tight">Projected Standings</h2>
            <div className="overflow-x-auto rounded-2xl border border-border/60 bg-card">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead className="w-10">#</TableHead>
                    <TableHead>Team</TableHead>
                    <TableHead className="text-right">Record</TableHead>
                    <TableHead className="text-right">Proj. Final</TableHead>
                    <TableHead className="text-right">Proj. PPG</TableHead>
                    <TableHead className="text-right">Playoff Odds</TableHead>
                    <TableHead className="text-right">Avg Finish</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {teamProjections.map((row, i) => (
                    <TableRow key={row.roster_id}>
                      <TableCell className="font-mono text-xs text-muted-foreground">{i + 1}</TableCell>
                      <TableCell>
                        <TeamBadge
                          name={row.team_name ?? row.manager?.display_name ?? `Team ${row.roster_id}`}
                          subtitle={row.manager?.display_name}
                          avatar={row.manager?.avatar}
                        />
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums text-muted-foreground">
                        {row.wins}-{row.losses}
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums">
                        {row.median_wins}-{regularSeasonWeeks - row.median_wins}
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums text-muted-foreground">
                        {fmtPoints(row.projected_lineup_ppg)}
                      </TableCell>
                      <TableCell
                        className={cn(
                          "text-right font-mono text-sm tabular-nums",
                          row.playoff_probability >= 0.66
                            ? "text-primary"
                            : row.playoff_probability <= 0.33
                              ? "text-destructive"
                              : "text-muted-foreground"
                        )}
                      >
                        {(row.playoff_probability * 100).toFixed(0)}%
                      </TableCell>
                      <TableCell className="text-right font-mono text-sm tabular-nums text-muted-foreground">
                        {row.avg_final_standing.toFixed(1)}
                        {row.avg_final_standing <= 1.5 && <Trophy className="ml-1 inline h-3 w-3 text-accent" />}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
            <p className="text-xs text-muted-foreground">
              &quot;Proj. Final&quot; is the median simulated record over {teamProjections[0]?.simulations.toLocaleString() ?? "10,000"} season
              simulations, seeded from each team&apos;s actual results so far. Playoff odds reflect this league&apos;s top {playoffTeams}{" "}
              seeds. A small league history (a few completed seasons) means these are directional, not precise — treat them as a
              data-informed guess, not a promise.
            </p>
          </section>
        </>
      )}
    </div>
  );
}
